### ISSUE TITLE
examples/beep.rs fails to compile

### ISSUE THREAD

**Issue by SephReed** [RustAudio/cpal#380]
These are my errors:
```
error[E0412]: cannot find type `StreamConfig` in crate `cpal`
  --> src/main.rs:22:49
   |
22 | fn run<T>(device: &cpal::Device, config: &cpal::StreamConfig) -> Result<(), anyhow::Error>
   |                                                 ^^^^^^^^^^^^ not found in `cpal`

error[E0599]: no method named `default_output_config` found for type `cpal::Device` in the current scope
  --> src/main.rs:11:25
   |
11 |     let config = device.default_output_config()?;
   |                         ^^^^^^^^^^^^^^^^^^^^^ method not found in `cpal::Device`

error[E0599]: no method named `build_output_stream` found for type `&cpal::Device` in the current scope
  --> src/main.rs:38:25
   |
38 |     let stream = device.build_output_stream(
   |                         ^^^^^^^^^^^^^^^^^^^ method not found in `&cpal::Device`

error: aborting due to 3 previous errors
```

This is the example:
https://github.com/RustAudio/cpal/blob/master/examples/beep.rs

-------

I really new to Rust, so I'm unable to figure out what syntax changes have occured.

**Comment by SephReed** [comment]
This function does appear to exist
https://github.com/RustAudio/cpal/blob/aac04e7263f31274885e0496fb1b2b0dd03c4477/src/host/coreaudio/mod.rs#L102

**Comment by est31** [comment]
That function was introduced by #371 which hasn't been in a crates.io release yet, only on master. I think you are using cpal from crates.io, while having copied the example code from git.

You can either get cpal from git (see [this](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories) link), or use the example code [from the 0.11.0 release](https://github.com/RustAudio/cpal/blob/fe9054f626b5bc466e3844f35b44476bfb614fb8/examples/beep.rs).

**Comment by SephReed** [comment]
Thank you!  You're the best!

**Comment by KillyMXI** [comment]
This got me confused too.

**Comment by gordonhart** [comment]
+1 to @KillyMXI's suggestion for tags on public releases. I'm willing to help out with the CI setup or manual retroactive tagging if needed!
